"""Initial schema

Revision ID: 994bb987f76a
Revises: 
Create Date: 2025-12-22 02:16:19.073784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994bb987f76a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ABSTAINED', name='runstatus'), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=False),
    sa.Column('request_type', sa.String(length=100), nullable=True),
    sa.Column('risk_label', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('final_answer', sa.Text(), nullable=True),
    sa.Column('abstention_reason', sa.Text(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('run_id')
    )
    op.create_index(op.f('ix_agent_runs_created_at'), 'agent_runs', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_runs_run_id'), 'agent_runs', ['run_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_status'), 'agent_runs', ['status'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('evaluation_id', sa.UUID(), nullable=False),
    sa.Column('benchmark_id', sa.String(length=100), nullable=False),
    sa.Column('eval_set_id', sa.String(length=100), nullable=True),
    sa.Column('backend', sa.String(length=50), nullable=False),
    sa.Column('mrr', sa.Float(), nullable=True),
    sa.Column('ndcg', sa.Float(), nullable=True),
    sa.Column('recall_at_k', sa.Float(), nullable=True),
    sa.Column('precision_at_k', sa.Float(), nullable=True),
    sa.Column('additional_metrics', sa.Text(), nullable=True),
    sa.Column('avg_latency_ms', sa.Float(), nullable=True),
    sa.Column('total_queries', sa.String(length=10), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('evaluated_by', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('evaluation_id')
    )
    op.create_index(op.f('ix_evaluations_backend'), 'evaluations', ['backend'], unique=False)
    op.create_index(op.f('ix_evaluations_benchmark_id'), 'evaluations', ['benchmark_id'], unique=False)
    op.create_index(op.f('ix_evaluations_eval_set_id'), 'evaluations', ['eval_set_id'], unique=False)
    op.create_index(op.f('ix_evaluations_evaluated_at'), 'evaluations', ['evaluated_at'], unique=False)
    op.create_index(op.f('ix_evaluations_evaluation_id'), 'evaluations', ['evaluation_id'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('prompt_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('template', sa.Text(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('version_id')
    )
    op.create_index(op.f('ix_prompt_versions_created_at'), 'prompt_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prompt_versions_prompt_name'), 'prompt_versions', ['prompt_name'], unique=False)
    op.create_index(op.f('ix_prompt_versions_version'), 'prompt_versions', ['version'], unique=False)
    op.create_index(op.f('ix_prompt_versions_version_id'), 'prompt_versions', ['version_id'], unique=False)
    op.create_table('grounding_verifications',
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('passed', sa.String(length=10), nullable=False),
    sa.Column('total_claims', sa.String(length=10), nullable=False),
    sa.Column('grounded_claims', sa.String(length=10), nullable=False),
    sa.Column('ungrounded_claims', sa.JSON(), nullable=True),
    sa.Column('issues', sa.JSON(), nullable=True),
    sa.Column('phi_redaction_count', sa.String(length=10), nullable=False),
    sa.Column('prompt_injection_detected', sa.String(length=10), nullable=False),
    sa.Column('verification_reason', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ),
    sa.PrimaryKeyConstraint('verification_id')
    )
    op.create_index(op.f('ix_grounding_verifications_run_id'), 'grounding_verifications', ['run_id'], unique=False)
    op.create_index(op.f('ix_grounding_verifications_status'), 'grounding_verifications', ['status'], unique=False)
    op.create_index(op.f('ix_grounding_verifications_verification_id'), 'grounding_verifications', ['verification_id'], unique=False)
    op.create_index(op.f('ix_grounding_verifications_verified_at'), 'grounding_verifications', ['verified_at'], unique=False)
    op.create_table('tool_calls',
    sa.Column('tool_call_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('backend', sa.String(length=50), nullable=True),
    sa.Column('inputs', sa.JSON(), nullable=False),
    sa.Column('outputs', sa.JSON(), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('success', sa.String(length=10), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ),
    sa.PrimaryKeyConstraint('tool_call_id')
    )
    op.create_index(op.f('ix_tool_calls_backend'), 'tool_calls', ['backend'], unique=False)
    op.create_index(op.f('ix_tool_calls_run_id'), 'tool_calls', ['run_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool_call_id'), 'tool_calls', ['tool_call_id'], unique=False)
    op.create_index(op.f('ix_tool_calls_tool_name'), 'tool_calls', ['tool_name'], unique=False)
    op.create_table('evidence_retrievals',
    sa.Column('retrieval_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tool_call_id', sa.UUID(), nullable=True),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('backend', sa.String(length=50), nullable=False),
    sa.Column('retrieval_mode', sa.String(length=50), nullable=True),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('doc_hashes', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ),
    sa.ForeignKeyConstraint(['tool_call_id'], ['tool_calls.tool_call_id'], ),
    sa.PrimaryKeyConstraint('retrieval_id')
    )
    op.create_index(op.f('ix_evidence_retrievals_backend'), 'evidence_retrievals', ['backend'], unique=False)
    op.create_index(op.f('ix_evidence_retrievals_retrieval_id'), 'evidence_retrievals', ['retrieval_id'], unique=False)
    op.create_index(op.f('ix_evidence_retrievals_retrieved_at'), 'evidence_retrievals', ['retrieved_at'], unique=False)
    op.create_index(op.f('ix_evidence_retrievals_run_id'), 'evidence_retrievals', ['run_id'], unique=False)
    op.create_index(op.f('ix_evidence_retrievals_tool_call_id'), 'evidence_retrievals', ['tool_call_id'], unique=False)
    op.create_table('citations',
    sa.Column('citation_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_position', sa.Integer(), nullable=True),
    sa.Column('doc_hash', sa.String(length=64), nullable=False),
    sa.Column('doc_title', sa.String(length=500), nullable=True),
    sa.Column('doc_section', sa.String(length=200), nullable=True),
    sa.Column('doc_url', sa.String(length=1000), nullable=True),
    sa.Column('retrieval_id', sa.UUID(), nullable=True),
    sa.Column('relevance_score', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['retrieval_id'], ['evidence_retrievals.retrieval_id'], ),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.run_id'], ),
    sa.PrimaryKeyConstraint('citation_id')
    )
    op.create_index(op.f('ix_citations_citation_id'), 'citations', ['citation_id'], unique=False)
    op.create_index(op.f('ix_citations_created_at'), 'citations', ['created_at'], unique=False)
    op.create_index(op.f('ix_citations_doc_hash'), 'citations', ['doc_hash'], unique=False)
    op.create_index(op.f('ix_citations_retrieval_id'), 'citations', ['retrieval_id'], unique=False)
    op.create_index(op.f('ix_citations_run_id'), 'citations', ['run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_citations_run_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_retrieval_id'), table_name='citations')
    op.drop_index(op.f('ix_citations_doc_hash'), table_name='citations')
    op.drop_index(op.f('ix_citations_created_at'), table_name='citations')
    op.drop_index(op.f('ix_citations_citation_id'), table_name='citations')
    op.drop_table('citations')
    op.drop_index(op.f('ix_evidence_retrievals_tool_call_id'), table_name='evidence_retrievals')
    op.drop_index(op.f('ix_evidence_retrievals_run_id'), table_name='evidence_retrievals')
    op.drop_index(op.f('ix_evidence_retrievals_retrieved_at'), table_name='evidence_retrievals')
    op.drop_index(op.f('ix_evidence_retrievals_retrieval_id'), table_name='evidence_retrievals')
    op.drop_index(op.f('ix_evidence_retrievals_backend'), table_name='evidence_retrievals')
    op.drop_table('evidence_retrievals')
    op.drop_index(op.f('ix_tool_calls_tool_name'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_tool_call_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_run_id'), table_name='tool_calls')
    op.drop_index(op.f('ix_tool_calls_backend'), table_name='tool_calls')
    op.drop_table('tool_calls')
    op.drop_index(op.f('ix_grounding_verifications_verified_at'), table_name='grounding_verifications')
    op.drop_index(op.f('ix_grounding_verifications_verification_id'), table_name='grounding_verifications')
    op.drop_index(op.f('ix_grounding_verifications_status'), table_name='grounding_verifications')
    op.drop_index(op.f('ix_grounding_verifications_run_id'), table_name='grounding_verifications')
    op.drop_table('grounding_verifications')
    op.drop_index(op.f('ix_prompt_versions_version_id'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_version'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_prompt_name'), table_name='prompt_versions')
    op.drop_index(op.f('ix_prompt_versions_created_at'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_evaluations_evaluation_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_evaluated_at'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_eval_set_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_benchmark_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_backend'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_status'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_run_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_created_at'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###

